Repository GustavEikaas/easy-dotnet.nvim, pull requests merged in 2024-09, with the labels that each got.

#93 feat: basic F# support
  lua/easy-dotnet/actions/build.lua
  lua/easy-dotnet/actions/clean.lua
  lua/easy-dotnet/actions/new.lua
  lua/easy-dotnet/actions/restore.lua
  lua/easy-dotnet/actions/run.lua
  lua/easy-dotnet/actions/test.lua
  lua/easy-dotnet/default-manager.lua
  lua/easy-dotnet/init.lua
  lua/easy-dotnet/parsers/csproj-parse.lua
  lua/easy-dotnet/parsers/sln-parse.lua
  lua/easy-dotnet/secrets.lua
  lua/easy-dotnet/test-runner/runner.lua
Labels: enhancement

#103 feat(testrunner): different viewmodes split/float/buf
  README.md
  lua/easy-dotnet/options.lua
  lua/easy-dotnet/test-runner/keymaps.lua
  lua/easy-dotnet/test-runner/render.lua
  lua/easy-dotnet/test-runner/runner.lua
  lua/easy-dotnet/test-runner/test-parser.lua
Labels: enhancement

#110 fix(sln-parse): rel path unix bug
  lua/easy-dotnet/parsers/sln-parse.lua
Labels: bug

#112 feat(testrunner): virtual text status top right corner
  lua/easy-dotnet/test-runner/keymaps.lua
  lua/easy-dotnet/test-runner/render.lua
  lua/easy-dotnet/test-runner/runner.lua
  lua/easy-dotnet/test-runner/test-parser.lua
Labels: enhancement

#115 feat: use msbuild for project version
  lua/easy-dotnet/debugger.lua
  lua/easy-dotnet/default-manager.lua
  lua/easy-dotnet/parsers/csproj-parse.lua
  lua/easy-dotnet/test-runner/runner.lua
Labels: enhancement

#104 add restore, build for testrunner
  README.md
  lua/easy-dotnet/async-utils.lua
  lua/easy-dotnet/options.lua
  lua/easy-dotnet/test-runner/keymaps.lua
  lua/easy-dotnet/test-runner/render.lua
  lua/easy-dotnet/test-runner/runner.lua
Labels: enhancement

#118 fix: disallow concurrent builds
  lua/easy-dotnet/actions/build.lua
Labels: bug

#120 feat: auto bootstrap interface
  lua/easy-dotnet/cs-mappings.lua
Labels: enhancement

#121 feat: add experimental support for debugging unit tests
  lua/easy-dotnet/debugger.lua
  lua/easy-dotnet/init.lua
Labels: enhancement

#122 feat: add support for extra args in Dotnet build|test|run
  README.md
  lua/easy-dotnet/actions/build.lua
  lua/easy-dotnet/actions/run.lua
  lua/easy-dotnet/actions/test.lua
  lua/easy-dotnet/init.lua
  lua/easy-dotnet/options.lua
Labels: enhancement

#123 feat(ef): add ef core integration
  README.md
  lua/easy-dotnet/ef-core/database.lua
  lua/easy-dotnet/ef-core/migration.lua
  lua/easy-dotnet/ef-core/utils.lua
  lua/easy-dotnet/init.lua
Labels: enhancement

#126 feat: allow more arguments to fallthrough from Dotnet commands
  README.md
  lua/easy-dotnet/actions/run.lua
  lua/easy-dotnet/init.lua
Labels: enhancement

#127 docs: update readme
  README.md
Labels: documentation

#128 fix(term): some term commands concatenated nil causing command to fail
  README.md
  lua/easy-dotnet/actions/build.lua
  lua/easy-dotnet/actions/restore.lua
  lua/easy-dotnet/actions/test.lua
  lua/easy-dotnet/ef-core/database.lua
  lua/easy-dotnet/ui-modules/spinner.lua
Labels: bug

#129 feat(cmp): add package autocomplete
  README.md
  lua/easy-dotnet/csproj-mappings.lua
  lua/easy-dotnet/init.lua
Labels: enhancement

#132 feat: add configurability to icons
  README.md
  lua/easy-dotnet/actions/test.lua
  lua/easy-dotnet/init.lua
  lua/easy-dotnet/options.lua
  lua/easy-dotnet/test-runner/keymaps.lua
  lua/easy-dotnet/test-runner/render.lua
  lua/easy-dotnet/test-runner/runner.lua
Labels: enhancement
