Repository GustavEikaas/easy-dotnet.nvim, pull requests merged in 2024-08, with the labels that each got.

#34 feat: add <leader>R for running all tests
  README.md
  lua/easy-dotnet/test-runner/keymaps.lua
Labels: enhancement

#42 fix: relative path conversion for sln parser (linux support)
  lua/easy-dotnet/parsers/sln-parse.lua
Labels: bug

#44 fix: no refresh when reopening buffer
  lua/easy-dotnet/test-runner/runner.lua
Labels: bug

#45 fix/no err message on failed test discovery
  lua/easy-dotnet/test-runner/render.lua
  lua/easy-dotnet/test-runner/runner.lua
Labels: bug

#46 feat(testrunner): toggle failed tests
  README.md
  lua/easy-dotnet/test-runner/keymaps.lua
  lua/easy-dotnet/test-runner/render.lua
  lua/easy-dotnet/test-runner/runner.lua
Labels: enhancement

#47 docs: add advanced configurations to the readme
  README.md
Labels: documentation

#49 feat(clean): add dotnet clean command
  README.md
  lua/easy-dotnet/actions/clean.lua
  lua/easy-dotnet/init.lua
Labels: enhancement

#51 feat(new): add dotnet new command
  README.md
  lua/easy-dotnet/actions/new.lua
  lua/easy-dotnet/init.lua
Labels: enhancement

#54 feat: auto bootstrap namespace when file is created
  README.md
  lua/easy-dotnet/cs-mappings.lua
  lua/easy-dotnet/init.lua
  lua/easy-dotnet/options.lua
Labels: enhancement

#59 fix(test): not discovering all test projects
  lua/easy-dotnet/parsers/csproj-parse.lua
Labels: bug

#63 docs: add dap example
  README.md
Labels: documentation

#69 feat(testrunner): v2 testrunner
  README.md
  lua/easy-dotnet/actions/build.lua
  lua/easy-dotnet/actions/restore.lua
  lua/easy-dotnet/constants.lua
  lua/easy-dotnet/debug.lua
  lua/easy-dotnet/default-manager.lua
  lua/easy-dotnet/options.lua
  lua/easy-dotnet/outdated/outdated.lua
  lua/easy-dotnet/test-runner/keymaps.lua
  lua/easy-dotnet/test-runner/render.lua
  lua/easy-dotnet/test-runner/runner.lua
  lua/easy-dotnet/test-runner/test-parser.lua
  lua/easy-dotnet/test-runner/window.lua
Labels: enhancement
